HTMLWidgets.widget({

  name: 'stmBrowser',

  type: 'output',

  initialize: function(el, width, height) {
    
    return {
      // TODO: add instance fields as required
    }

  },

  renderValue: function(el, x, instance) {
    
    el.innerHTML = [
      '<div id="container"></div>',
      '<div id="bottom"></div>',
      '<div id="credit">',
      '  <text>Generated by <a href="https://github.com/mroberts/stmBrowser" target="_blank">stmBrowser</a></text>',
      '</div>'
    ].join('\n')
    
    window.data = x.data.data;
    window.topics = x.data.topics;
    
    instance.view = new TextView(settings.textView)    

  },

  resize: function(el, width, height, instance) {

  }
  

});