HTMLWidgets.widget({

  name: 'stmBrowser',

  type: 'output',

  initialize: function(el, width, height) {
    
    return {
      // TODO: add instance fields as required
    }

  },

  renderValue: function(el, x, instance) {
    
    // for now get a scoped version of settings
    //   need to get rid of the global/window settings from settings.js
    var settings = window.settings.textView;
    settings.data = x.data.data;
    
    el.innerHTML = [
      '<div id="container"></div>',
      '<div id="bottom"></div>',
      '<div id="credit">',
      '  <text>Generated by <a href="https://github.com/mroberts/stmBrowser" target="_blank">stmBrowser</a></text>',
      '</div>'
    ].join('\n')
    
    // also need to eliminate this global/window variable
    //   for now though do the ugly
    window.data = x.data.data;
    window.topics = x.data.topics;
    
    instance.view = new TextView(settings)    

  },

  resize: function(el, width, height, instance) {

  }
  

});